config/routes.rb
Rails.application.routes.draw do
  get 'errors/not_found'
  get 'errors/internal_server_error'
  devise_for :users, :controllers => { registrations: 'registrations' }
  root "pages#show", page: "home"

  resources :articles do
    resources :comments
  end

  resources :contacts, only: [:new, :create]

  get "/pages/:page" => "pages#show"
  get "pages/menu", :as => "menu_page"
  get "pages/about", :as => "about_page"
  get "contacts/new", :as => "contact_page"

  match "/404", to: "errors#not_found", via: :all
  match "/500", to: "errors#internal_server_error", via: :all
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
  validates :title, presence: true
  validates :body, presence: true, length: { minimum: 10 }

    has_many :comments
    belongs_to :user
    has_one_attached :image

end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :article
end

app/models/contact.rb
class Contact < MailForm::Base
  attribute :name
  attribute :email
  attribute :message
  attribute :date
  attribute :number
  attribute :nickname,  captcha: true

  # Declare the e-mail headers. It accepts anything the mail method
  # in ActionMailer accepts.
  def headers
    {
      :subject => "Contact Form Inquiry",
      :to => "justjohnd@gmail.com",
      :from => %("#{name}" <#{email}>)
    }
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  # validates :username, presence: true, length: { in: 2..25 }
  # validates :nameLast, presence: true, length: { in: 2..25 }
  # validates :nameFirst, presence: true, length: { in: 2..25 }

  has_many :articles
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

before_action :set_locale

  def set_locale
    if user_signed_in?
      I18n.locale = current_user.language
    else
      I18n.locale = params[:lang] || locale_from_header || I18n.default_locale
    end
  end

  def locale_from_header
    request.env.fetch('HTTP_ACCEPT_LANGUAGE', '').scan(/[a-z]{2}/).first
  end

  def default_url_options
  { lang: I18n.locale }
end



end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_action :authenticate_user!, except: [:index, :show]

  def index
    @articles = Article.all
  end

  def show
    @article = Article.find(params[:id])
  end

  def new
    @article = current_user.articles.build
  end

  def create
    @article = current_user.articles.build(article_params)

    if @article.save
      redirect_to @article
    else
      render :new
    end
  end

  def edit
    @article = Article.find(params[:id])
  end

  def update
    @article = Article.find(params[:id])

    if @article.update(article_params)
      redirect_to @article
    else
      render :edit
    end
  end

  def destroy
    @article = Article.find(params[:id])
    @article.destroy

    redirect_to root_path
  end

  private
  def article_params
    params.require(:article).permit(:title, :body, :image)
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def create
    @article = Article.find(params[:article_id])
    @comment = @article.comments.create(comment_params)
    redirect_to article_path(@article)
  end

  private
    def comment_params
      params.require(:comment).permit(:commenter, :body)
    end
end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController

def new
  @contact = Contact.new
end

def create
  @contact = Contact.new(contacts_params)
  @contact.request = request
  if @contact.deliver
    flash.now[:success] = 'Message sent!'
  else
    flash.now[:error] = 'Could not send message'
    render :new
  end
end

  private
  def contacts_params
    params.require(:contact).permit(:name, :email, :date, :number, :message)
  end

end

app/controllers/errors_controller.rb
class ErrorsController < ApplicationController
  def not_found
    render status: 404
  end

  def internal_server_error
    render status: 500
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def show
    render "pages/#{params[:page]}"
  end
end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController

  private
  def sign_up_params
    params.require(:user).permit(:nameLast, :nameFirst, :username, :email, :password, :confirm_password, :language)
  end

    def account_update_params
    params.require(:user).permit(:nameLast, :nameFirst, :username, :email, :password, :current_password, :confirm_password, :language)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/helpers/errors_helper.rb
module ErrorsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/articles/_form.html.erb
  <%= form_with model: article do |form| %>
  <div>
    <%= form.label :title %><br />
    <%= form.text_field :title, class: "form-input" %><br />
    <% article.errors.full_messages_for(:title).each do |message| %>
      <div><%= message %></div>
    <% end %>
  </div>
  <div>
    <%= form.label :body %><br />
    <%= form.text_area :body, class: "form-input body-field" %><br />
    <% article.errors.full_messages_for(:body).each do |message| %>
      <div><%= message %></div>
    <% end %>
  </div>
  <div>
    <%= form.label :image %>
    <%= form.file_field :image %>
  </div>
  <div>
    <%= form.submit "Submit", class: "btn mt-16" %>
  </div>
<% end %>

app/views/articles/edit.html.erb
<h1>Edit Article</h1>

<%= render "form", article: @article %>

app/views/articles/index.html.erb
<%= render "shared/header" %>
<section class="page-container">
  <h1 class="articles-title"><%= t('blog_title') %></h1>
  <ul class="article">
    <% @articles.each do | article | %>
      <li class="article-title"><%= link_to article.title, article %></li>
      <li class="article-subtitle">
        By <%= article.user.username %> - <%= article.created_at.strftime("%d %b. %Y") %>
      </li>
      <li>
        <div class="article-image">
          <%= image_tag(article.image, class: "image") %>
        </div>
      </li>
      <li class="article-body">
        <%= truncate(article.body, length: 300) {link_to "...Read More", article}
      %>
      </li>
    <% end %>
  </ul>
  <div class="mt-36">
    <% if user_signed_in? %>
      <%= link_to "New Article", new_article_path %>
    <% end %>
  </div>
</section>
<%= render "shared/footer_with_wrapper" %>

app/views/articles/new.html.erb
<%= render "shared/header" %>
<div class="new-article-container">
  <h1>New Article</h1>
  <%= render "form", article: @article %>
</div>

app/views/articles/show.html.erb
<%= render "shared/header" %>
<section class="page-container">
  <h1><%= @article.title %></h1>
  <p class="article-subtitle">
    By <%= @article.user.username %> - <%= @article.created_at.strftime("%d %b. %Y") %>
  </p>
  <div class="article-image">
    <%= image_tag(@article.image, class: "image") %>
  </div>
  <p><%= @article.body %></p>
</section>
<div class="edit-section">
  <ul>
    <li><%= link_to "Edit", edit_article_path(@article) %></li>
    <li>
      <%= link_to "Destroy", article_path(@article), method: :delete, data: {
    confirm: "Are you sure?" } %>
    </li>
    <li><%= link_to "Back to articles", articles_path %></li>
  </ul>
</div>
<%= render "shared/footer_with_wrapper" %>

app/views/comments/_comment.html.erb
<p>
  <strong>Commenter:</strong>
  <%= comment.commenter %>
</p>

<p>
  <strong>Comment:</strong>
  <%= comment.body %>
</p>

app/views/comments/_form.html.erb
<%= form_with model: [ @article, @article.comments.build ] do |form| %>
  <p>
    <%= form.label :commenter %><br>
    <%= form.text_field :commenter %>
  </p>
  <p>
    <%= form.label :body %><br>
    <%= form.text_area :body %>
  </p>
  <p>
    <%= form.submit %>
  </p>
<% end %>

app/views/contacts/create.html.erb
<%= render "shared/header" %>
<section class="page-container">
  <h1 class="page-title mb-36"><%= t('reservations') %></h1>
  <div class="article mb-36">
    <div class="article-body mb-12">
      <h3>Thank you for your message!</h3>
    </div>
  </div>
  <div class="article mb-36">
    <div class="article-title ">
      CANCELLATION POLICY</div>
    <div class="article-body">
      <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.</p>
    </div>
  </div>
</section>
<%= render "shared/footer_with_wrapper" %>

app/views/contacts/new.html.erb
<%# This page is linked to from Reservations %>
<%= render "shared/header" %>
<section class="page-container">
  <h1 class="page-title mb-36"><%= t('reservations') %></h1>
  <div class="article mb-36">
    <div class="article-body mb-12">
      <%= t('res_description_html') %>
    </div>
  </div>
  <div class="article mb-36">
    <div class="article-title ">
      CANCELLATION POLICY</div>
    <div class="article-body">
      <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.</p>
    </div>
  </div>
  <h1 class="article-title">CONTACT</h1>
  <p class="mb-12"><%= t('contact_info') %></p>
  <%= simple_form_for @contact do |f| %>
    <div class="field">
      <%= f.label t('form_name') %></br>
    <%= f.text_field  :name, required: true, class: "contact-form-text-area form-input" %>
  </div>
  <div class="field">
    <%= f.label t('form_number') %><br />
    <%= f.select :number, [1, 2, 3, 4, 5, 6, 7, 8, 9, 10], include_blank: true, required: false, class: "form-input contact-form-text-area" %>
  </div>
  <div class="field">
    <%= f.label t('form_date') %><br />
    <%= f.date_field :date, required: false, class: "contact-form-text-area form-input" %>
  </div>
  <div class="field">
    <%= f.label :email %><br />
    <%= f.email_field :email, required: true, class: "contact-form-text-area form-input" %>
  </div>
  <div class="field">
    <%= f.label :message %><br />
    <%= f.text_area :message, rows: 8, cols: 40, required: true, class: "contact-form-text-area form-input body-field", placeholder: "Send us a message"%>
  </div>
  <div class= "d-none">
    <%= f.label :nickname %>
    <%= f.text_field :nickname, :hint => 'Leave this field blank!' %>
  </div>
  <%= f.submit 'Send Message', class: 'btn' %>
<% end %>
</section>
<%= render "shared/footer_with_wrapper" %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Aster Reste</title>
    <meta name="viewport" content="width=device-width,initial-scale=1" />
    <%= csrf_meta_tags %> <%= csp_meta_tag %>
    <!--  -->
    <%= stylesheet_link_tag 'application', media: 'all',
    'data-turbolinks-track': 'reload' %>
    <!--  -->
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <!--  -->
    <link rel="preconnect" href="https://fonts.googleapis.com" />
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin />
    <%= stylesheet_link_tag 'application',
    'https://fonts.googleapis.com/css2?family=Work+Sans:wght@100;200;300;500;700&display=swap'
    %>
    <%= favicon_link_tag asset_path('magnolia.ico') %>
  </head>
  <body>
    <% if flash[:notice] %>
      <p class="notice"><%= notice %></p>
    <% end %> <% if flash[:alert] %>
      <p class="alert"><%= alert %></p>
    <% end %>
    <%# Flash notice for contact form %>
    <% if flash[:alert] %>
      <div class="container">
        <br>
        <% flash.each do |key, message| %>
          <p class="alert alert-<%= key %>"><%= message %></p>
        <% end %>
      </div>
    <% end %>
    <%= yield %>
    <%= javascript_pack_tag 'hamburger' %>
    <%# Change mobile menu height based on whether user is signed in or not %>
    <% if user_signed_in? %>
      <script type="text/javascript" charset="utf-8">
        document.querySelector('.mobile-menu').classList.add('long');
        
        if (document.querySelector('.mobile-menu').classList.contains('short')) {
          document.querySelector('.mobile-menu').classList.remove('short');
        }
      </script>
    <% else %>
      <script type="text/javascript" charset="utf-8">
        document.querySelector('.mobile-menu').classList.add('short');
        
        if (document.querySelector('.mobile-menu').classList.contains('long')) {
          document.querySelector('.mobile-menu').classList.classList.remove('long');
        }
      </script>
    <% end %>
  </body>
</html>

app/views/pages/about.html.erb
<%= render "shared/header" %>
<section class="page-container">
  <h1 class="page-title mb-36"><%= t('about_title') %></h1>
  <div class="article mb-36">
    <%# <div class="article-title ">
      It all started in a sleepy little town called Portland...</div> %>
    <div class="article-body">
      <p><%= t('about_body_1') %></p>
      <br/>
      <p><%= t('about_body_2') %></p>
      <br/>
      <p><%= t('about_body_3') %></p>
      <br/>
    </div>
  </div>
  <div class="article mb-36">
    <div class="article-title ">
      <%= t('about_con_title') %></div>
    <br/>
    <div class="article-body">
      <p><%= t('about_con_body') %></p>
      <br/>
      <p><%= t('about_add_1') %></p>
      <p><%= t('about_add_2') %></p>
      <p>
        <a
          href="https://goo.gl/maps/qivmSfBRyTC9MbUY8"
          target="_blank"
          rel="noopener noreferrer"
          ><%= t('about_map') %></a
        >
      </p>
    </div>
  </div>
</section>
<%= render "shared/footer_with_wrapper" %>

app/views/pages/home.html.erb
<div class="front-page-wrapper">
  <%= render "shared/logout_links" %>
  <%= render "shared/mobile_menu" %>
  <section class="front-page">
    <aside class="container-aside">
      <header>
        <div class="site-name">Aster</div>
        <nav>
          <ul class="menu">
            <%= render "shared/nav_menu" %>
          </ul>
        </nav>
      </header>
      <footer class="footer-aside">
        <ul>
          <li class="mb-12">
            <div>81. Tarn. France. </div>
            <div>
              <a
                href="https://goo.gl/maps/qivmSfBRyTC9MbUY8"
                target="_blank"
                rel="noopener noreferrer"
                ><%= t('see_map') %></a
              >
            </div>
          </li>
          <li><%= t('footer_phone') %>: xxx-xxx-xxx</li>
          <li><%= t('footer_hours') %>: <%= t('footer_monday') %>-<%= t('footer_saturday') %>, 17:00-23:00</li>
        </ul>
      </footer>
    </aside>
    <h1 class="mobile-site-name site-name">Aster</h1>
    <div class="front-page-img-wrapper">
      <%= image_tag("cover-img.jpg", :class => "front-page-img") %>
      <div class="socials-wrapper">
        <%= render "shared/socials" %>
      </div>
    </div>
  </section>
  <%= render "shared/footer" %>
</div>

app/views/pages/menu.html.erb
<%= render "shared/header" %>
<section class="page-container">
  <h1 class="page-title mb-36"><%= t('menu_pg_title') %></h1>
  <div class="article mb-36">
    <div class="article-title ">
      <%= t('menu_pg_season') %>
    </div>
    <div class="article-subtitle"><em><%= t('menu_pg_period') %></em></div>
    <div class="article-body">
      <p><%= t('menu_pg_desc') %></p>
    </div>
    <div class="article-body">
      <p><%= t('menu_pg_menu') %></p>
      <p><%= t('menu_pg_wine') %></p>
      <p><%= t('menu_pg_juice') %></p>
    </div>
    <div class="gallery-con">
      <%= image_tag("food-1.jpg", :class => "image-1") %>
      <%= image_tag("food-2.jpg", :class => "image-2") %>
    </div>
    <div class="gallery-con">
      <%= image_tag("food-3.jpg", :class => "image-3") %>
    </div>
  </div>
  <%# Additional spring season %>
  <%# <div class="article mb-36">
    <div class="article-title ">
      SPRING SEASON</div>
    <div class="article-subtitle"><em>March 22nd - June 21st</em></div>
    <div class="article-body">
      <p>This menu will be a celebration of fall abundance and the period of the year when meat will play a starring role at noma. Expect lots of preserved greens and flowers that we have foraged over the summer, together with mushrooms, berries and everything the forest has to offer.</p>
    </div>
    <div class="article-body">
      <p>Menu: DKK 2,800</p>
      <p>Wine Pairing: DKK 1,800</p>
      <p>Juice Pairing: DKK 1,000</p>
    </div>
  </div> %>
  <div class="article">
    <div class="article-title "><%= t('menu_pg_wines') %></div>
    <div class="article-body">
      <p><%= t('menu_pg_wine_desc') %></p>
    </div>
    <div class="gallery-con">
      <%= image_tag("wine-1.jpg", :class => "image-4") %>
      <%= image_tag("wine-2.jpg", :class => "image-5") %>
    </div>
    <div class="gallery-con">
      <%= image_tag("wine-3.jpg", :class => "image-6") %>
    </div>
  </div>
</div>
</section>
<%= render "shared/footer_with_wrapper" %>

app/views/shared/_footer.html.erb
<div class="footer-bottom">
  <ul class="footer-bottom-items">
    <li class="footer-bottom-item">
      <div>81. Tarn. France.</div>
      <div>
        <a
          href="https://goo.gl/maps/qivmSfBRyTC9MbUY8"
          target="_blank"
          rel="noopener noreferrer"
          >See map</a
        >
      </div>
    </li>
    <li class="footer-bottom-item">
      <div>Phone</div>
      <div>xxx-xxx-xxx</div>
    </li>
  </li>
  <li class="footer-bottom-item">
    <div>Opening Hours</div>
    <div>Saturday Evenings 17:00~</div>
  </li>
</ul>
</div>

app/views/shared/_footer_with_wrapper.html.erb
<div class="footer-bottom-wrapper">
  <h3 class="footer-bottom-title">Aster Reste</h3>
  <%= render "shared/footer" %>
</div>

app/views/shared/_header.html.erb
<%= render "shared/mobile_menu" %>
<header class="banner">
  <div class="socials-wrapper">
    <%= render "shared/socials" %>
  </div>
  <%= image_tag "cover-img-1200.jpg", :class => "front-page-img"%>
  <%= render "shared/logout_links" %>
  <nav class="banner-nav-wrapper">
    <div class="site-name"><%= link_to "Aster", root_path %></div>
    <div class="menu-wrapper">
      <ul class="menu">
        <li class="menu-item"><%= link_to t('menu_food'), menu_page_path %></li>
        <li class="menu-item"><%= link_to t('menu_reservations'), contact_page_path %></li>
        <li class="menu-item"><%= link_to t('menu_blog'), articles_path %></li>
        <li class="menu-item"><%= link_to t('menu_about'), about_page_path %></li>
      </ul>
      <div class="menu menu-item"><%= link_to("english", url_for(lang: :en))
 %><span>&nbsp;/&nbsp;</span><%= link_to("francais", url_for(lang: :fr))
 %></div>
    </div>
  </nav>
</header>

app/views/shared/_logout_links.html.erb
  
<div class="logout-container">
  <% if user_signed_in? %>
    <p class="control">
      <%= link_to "Account", edit_user_registration_path, class: "account-link" %>
    </p>
    <p>
      <%= link_to "Logout", destroy_user_session_path, method: :delete, class: "account-link" %>
    </p>
  <% end %>
</div>

app/views/shared/_mobile_menu.html.erb
<section class="mobile-wrapper">
  <div class="nav-mobile">
    <div class="hamburger">
      <%= fa_icon 'times', :class => 'hamburger-close' %>
      <div class="line"></div>
      <div class="line"></div>
      <div class="line"></div>
    </div>
  </div>
  <ul class="mobile-menu d-none">
    <%= render "shared/nav_menu" %>
    <div class="mobile-socials-wrapper">
      <%= render "shared/socials" %>
    </div>
    <li class="menu-item">
      <% if user_signed_in? %>
        <p>
          <%= link_to "Account", edit_user_registration_path, class: "account-link" %>
        </p>
        <p>
          <%= link_to "Logout", destroy_user_session_path, method: :delete, class: "account-link" %>
        </p>
      <% end %>
    </li>
  </ul>
</section>

app/views/shared/_nav_menu.html.erb
<li class="menu-item"><%= link_to t('menu_food'), menu_page_path %></li>
<li class="menu-item"><%= link_to t('menu_reservations'), contact_page_path %></li>
<li class="menu-item"><%= link_to t('menu_blog'), articles_path %></li>
<li class="menu-item"><%= link_to t('menu_about'), about_page_path %></li>
<li class="menu-item"><%= link_to("english", url_for(lang: :en)) %><span>&nbsp;/&nbsp;</span><%= link_to("francais", url_for(lang: :fr)) %></li>

app/views/shared/_socials.html.erb
    <a href="https://www.facebook.com/aster.resto.81" target="_blank" rel="noopener noreferrer">
  <%= fa_icon 'facebook', :class => 'social' %>
</a>
<a href="https://www.instagram.com/aster.restaurant/" target="_blank" rel="noopener noreferrer">
  <%= fa_icon 'instagram', :class => 'social' %>
</a>